import streamlit as st
import json
from pathlib import Path

st.set_page_config(
    page_title="E-Commerce Analytics",
    page_icon="🛒",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ── Load insights report (generated by notebook 06) ──────────────────────────
INSIGHTS_PATH = Path("outputs/summaries/insights_report.json")

@st.cache_data
def load_insights():
    if INSIGHTS_PATH.exists():
        return json.loads(INSIGHTS_PATH.read_text())
    return None

insights = load_insights()

# ── Sidebar ───────────────────────────────────────────────────────────────────
st.sidebar.title("🛒 E-Commerce Analytics")
st.sidebar.markdown("---")
st.sidebar.caption("Databricks Analytics Pipeline")

if insights:
    st.sidebar.success(f"Data updated: {insights['generated_at'][:10]}")
else:
    st.sidebar.warning("No insights data found. Run Databricks pipeline first.")

# ── Home / KPI overview ───────────────────────────────────────────────────────
st.title("E-Commerce Analytics Dashboard")
st.markdown("Overview of the full pipeline: **5M orders → Databricks ETL → ML → Insights**")

if insights:
    kpis = insights["kpis"]
    c1, c2, c3, c4, c5, c6 = st.columns(6)
    c1.metric("Total Orders",     f"{kpis['total_orders']:,}")
    c2.metric("Total Revenue",    f"${kpis['total_revenue']:,.0f}")
    c3.metric("Avg Order Value",  f"${kpis['avg_order_value']:,.2f}")
    c4.metric("Unique Customers", f"{kpis['unique_customers']:,}")
    c5.metric("Delivery Rate",    f"{kpis['delivery_rate_pct']}%")
    c6.metric("Cancellation",     f"{kpis['cancellation_rate_pct']}%")

    st.markdown("---")

    col_left, col_right = st.columns(2)

    with col_left:
        st.subheader("💡 Revenue Insights")
        for insight in insights.get("revenue_insights", []):
            st.info(insight)

    with col_right:
        st.subheader("🏷️ Category Insights")
        for insight in insights.get("category_insights", []):
            st.info(insight)

    st.subheader("👥 Customer Segment Insights")
    for insight in insights.get("cluster_insights", []):
        st.success(insight)
else:
    st.info("Run the Databricks pipeline (notebook 07) then place the outputs/ folder here.")
    st.code("databricks fs cp dbfs:/FileStore/ecommerce/outputs/ ./outputs/ --recursive")

st.markdown("---")
st.caption("Navigate the pages in the sidebar for detailed analytics →")
